swagger: "2.0"
info:
  description: This is a simple calendar API
  version: 2.0.0
  title: Calendar API
  contact:
    email: ionut.cicio@marconicloud.it

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers

paths:
  /events:
    get:
      tags:
        - developers
      summary: gets all events
      operationId: getEvents
      description: |
        You can get all the events present in the system
      produces:
        - application/json
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: "#/definitions/Event"
        400:
          description: bad input parameter
  /events/{id}:
    get:
      tags:
        - developers
      summary: details of an event
      operationId: eventDetails
      description: |
        You can get the partecipants of an event
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          type: integer
          required: true
          minimum: 1
      responses:
        200:
          description: get an event with partecpiants
          schema:
            $ref: "#/definitions/EventDetails"
        400:
          description: bad input parameter
definitions:
  Event:
    type: object
    required:
      - id
      - title
      - organizer
      - cost
    properties:
      id:
        type: number
        example: 2
      title:
        type: string
        example: "Seminario Social"
      organizer:
        type: string
        example: "Claudio Capobianco"
      cost:
        type: number
        example: 12
  EventDetails:
    type: object
    required:
      - id
      - title
      - organizer
      - cost
      - participants
    properties:
      id:
        type: number
        example: 5
      title:
        type: string
        example: "Seminario SQL"
      organizer:
        type: string
        example: "Gianluigi Luigi"
      cost:
        type: number
        example: 13
      participants:
        type: array
        items:
          type: string
        example: ["Claudio Mancini", "Salvatore Aranzulla"]

# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /IonutCicio/calendar/2.0.0
schemes:
  - https
